on: workflow_dispatch
name: Build Release
run-name: Building Release ⛏️
jobs:
  build-for-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
      - name: Build Application for Windows AMD64
        run: GOOS=windows GOARCH=amd64 go build -o bin/windows-amd64/leagueofascii.exe .
      - name: Build Application for Windows ARM64
        run: GOOS=windows GOARCH=arm64 go build -o bin/windows-arm64/leagueofascii.exe .
      - name: Build Application for Linux AMD64 
        run: GOOS=linux GOARCH=amd64 go build -o bin/linux-amd64/leagueofascii .
      - name: Build Application for Linux ARM64
        run: GOOS=linux GOARCH=arm64 go build -o bin/linux-arm64/leagueofascii .
      - name: Build Application for Mac AMD64
        run: GOOS=darwin GOARCH=amd64 go build -o bin/darwin-amd64/leagueofascii .
      - name: Build Application for Mac ARM64
        run: GOOS=darwin GOARCH=arm64 go build -o bin/darwin-ard64/leagueofascii .
      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: ./bin/**
